export const datosPorPais = {
  Argentina: {
    moneda: "ARS",
    tasaCreditoConsumo: 60,
    tasaCreditoAuto: 55,
    tasaCreditoVivienda: 45,
    tasaInversion: 50,
    valorPropiedadPromedio: 25000000,
  },
  Bolivia: {
    moneda: "BOB",
    tasaCreditoConsumo: 18,
    tasaCreditoAuto: 16,
    tasaCreditoVivienda: 10,
    tasaInversion: 7,
    valorPropiedadPromedio: 500000,
  },
  Brasil: {
    moneda: "BRL",
    tasaCreditoConsumo: 30,
    tasaCreditoAuto: 25,
    tasaCreditoVivienda: 12,
    tasaInversion: 9,
    valorPropiedadPromedio: 350000,
  },
  Chile: {
    moneda: "CLP",
    tasaCreditoConsumo: 8,
    tasaCreditoAuto: 7.5,
    tasaCreditoVivienda: 4.2,
    tasaInversion: 6.5,
    valorPropiedadPromedio: 120000000,
  },
  Colombia: {
    moneda: "COP",
    tasaCreditoConsumo: 15,
    tasaCreditoAuto: 13,
    tasaCreditoVivienda: 9.5,
    tasaInversion: 8.2,
    valorPropiedadPromedio: 250000000,
  },
  Ecuador: {
    moneda: "USD",
    tasaCreditoConsumo: 14,
    tasaCreditoAuto: 12,
    tasaCreditoVivienda: 8,
    tasaInversion: 6.5,
    valorPropiedadPromedio: 90000,
  },
  Guyana: {
    moneda: "GYD",
    tasaCreditoConsumo: 20,
    tasaCreditoAuto: 18,
    tasaCreditoVivienda: 12,
    tasaInversion: 7,
    valorPropiedadPromedio: 15000000,
  },
  Paraguay: {
    moneda: "PYG",
    tasaCreditoConsumo: 16,
    tasaCreditoAuto: 14,
    tasaCreditoVivienda: 10,
    tasaInversion: 7.5,
    valorPropiedadPromedio: 400000000,
  },
  Perú: {
    moneda: "PEN",
    tasaCreditoConsumo: 11,
    tasaCreditoAuto: 9,
    tasaCreditoVivienda: 7.2,
    tasaInversion: 6.9,
    valorPropiedadPromedio: 350000,
  },
  Surinam: {
    moneda: "SRD",
    tasaCreditoConsumo: 22,
    tasaCreditoAuto: 20,
    tasaCreditoVivienda: 14,
    tasaInversion: 8,
    valorPropiedadPromedio: 300000,
  },
  Uruguay: {
    moneda: "UYU",
    tasaCreditoConsumo: 12,
    tasaCreditoAuto: 10,
    tasaCreditoVivienda: 6.5,
    tasaInversion: 6,
    valorPropiedadPromedio: 2500000,
  },
  Venezuela: {
    moneda: "VES",
    tasaCreditoConsumo: 40,
    tasaCreditoAuto: 35,
    tasaCreditoVivienda: 25,
    tasaInversion: 20,
    valorPropiedadPromedio: 150000,
  },

  // Caribe
  Cuba: {
    moneda: "CUP",
    tasaCreditoConsumo: 20,
    tasaCreditoAuto: 18,
    tasaCreditoVivienda: 12,
    tasaInversion: 7,
    valorPropiedadPromedio: 300000,
  },
  República Dominicana: {
    moneda: "DOP",
    tasaCreditoConsumo: 22,
    tasaCreditoAuto: 20,
    tasaCreditoVivienda: 14,
    tasaInversion: 8,
    valorPropiedadPromedio: 4500000,
  },
  Haití: {
    moneda: "HTG",
    tasaCreditoConsumo: 30,
    tasaCreditoAuto: 28,
    tasaCreditoVivienda: 18,
    tasaInversion: 10,
    valorPropiedadPromedio: 1500000,
  },
  Jamaica: {
    moneda: "JMD",
    tasaCreditoConsumo: 25,
    tasaCreditoAuto: 22,
    tasaCreditoVivienda: 15,
    tasaInversion: 9,
    valorPropiedadPromedio: 8000000,
  },
  Trinidad y Tobago: {
    moneda: "TTD",
    tasaCreditoConsumo: 18,
    tasaCreditoAuto: 16,
    tasaCreditoVivienda: 10,
    tasaInversion: 7,
    valorPropiedadPromedio: 1200000,
  },
  Barbados: {
    moneda: "BBD",
    tasaCreditoConsumo: 15,
    tasaCreditoAuto: 13,
    tasaCreditoVivienda: 9,
    tasaInversion: 6.5,
    valorPropiedadPromedio: 1000000,
  },
  Bahamas: {
    moneda: "BSD",
    tasaCreditoConsumo: 14,
    tasaCreditoAuto: 12,
    tasaCreditoVivienda: 8,
    tasaInversion: 6,
    valorPropiedadPromedio: 200000,
  },
};
