Chile: {
  moneda: "CLP",
  simbolo: "$",
  nombreDivisa: "Peso chileno",
  codigoISO: "CLP",
  tasaCreditoConsumo: 8,
  tasaCreditoAuto: 7.5,
  tasaCreditoVivienda: 4.2,
  tasaInversion: 6.5,
  valorPropiedadPromedio: 120000000,
},

Perú: {
  moneda: "PEN",
  simbolo: "S/",
  nombreDivisa: "Sol peruano",
  codigoISO: "PEN",
  tasaCreditoConsumo: 11,
  tasaCreditoAuto: 9,
  tasaCreditoVivienda: 7.2,
  tasaInversion: 6.9,
  valorPropiedadPromedio: 350000,
},

Argentina: {
  moneda: "ARS",
  simbolo: "$",
  nombreDivisa: "Peso argentino",
  codigoISO: "ARS",
  tasaCreditoConsumo: 60,
  tasaCreditoAuto: 55,
  tasaCreditoVivienda: 45,
  tasaInversion: 50,
  valorPropiedadPromedio: 25000000,
},

Colombia: {
  moneda: "COP",
  simbolo: "$",
  nombreDivisa: "Peso colombiano",
  codigoISO: "COP",
  tasaCreditoConsumo: 15,
  tasaCreditoAuto: 13,
  tasaCreditoVivienda: 9.5,
  tasaInversion: 8.2,
  valorPropiedadPromedio: 250000000,
},

México: {
  moneda: "MXN",
  simbolo: "$",
  nombreDivisa: "Peso mexicano",
  codigoISO: "MXN",
  tasaCreditoConsumo: 12,
  tasaCreditoAuto: 10.5,
  tasaCreditoVivienda: 8.0,
  tasaInversion: 7.8,
  valorPropiedadPromedio: 1800000,
},

Uruguay: {
  moneda: "UYU",
  simbolo: "$",
  nombreDivisa: "Peso uruguayo",
  codigoISO: "UYU",
  tasaCreditoConsumo: 12,
  tasaCreditoAuto: 10,
  tasaCreditoVivienda: 6.5,
  tasaInversion: 6,
  valorPropiedadPromedio: 2500000,
},

Paraguay: {
  moneda: "PYG",
  simbolo: "₲",
  nombreDivisa: "Guaraní paraguayo",
  codigoISO: "PYG",
  tasaCreditoConsumo: 16,
  tasaCreditoAuto: 14,
  tasaCreditoVivienda: 10,
  tasaInversion: 7.5,
  valorPropiedadPromedio: 400000000,
},

Bolivia: {
  moneda: "BOB",
  simbolo: "Bs",
  nombreDivisa: "Boliviano",
  codigoISO: "BOB",
  tasaCreditoConsumo: 18,
  tasaCreditoAuto: 16,
  tasaCreditoVivienda: 10,
  tasaInversion: 7,
  valorPropiedadPromedio: 500000,
},

Brasil: {
  moneda: "BRL",
  simbolo: "R$",
  nombreDivisa: "Real brasileño",
  codigoISO: "BRL",
  tasaCreditoConsumo: 30,
  tasaCreditoAuto: 25,
  tasaCreditoVivienda: 12,
  tasaInversion: 9,
  valorPropiedadPromedio: 350000,
},

Ecuador: {
  moneda: "USD",
  simbolo: "$",
  nombreDivisa: "Dólar estadounidense",
  codigoISO: "USD",
  tasaCreditoConsumo: 14,
  tasaCreditoAuto: 12,
  tasaCreditoVivienda: 8,
  tasaInversion: 6.5,
  valorPropiedadPromedio: 90000,
},

Venezuela: {
  moneda: "VES",
  simbolo: "Bs",
  nombreDivisa: "Bolívar digital",
  codigoISO: "VES",
  tasaCreditoConsumo: 40,
  tasaCreditoAuto: 35,
  tasaCreditoVivienda: 25,
  tasaInversion: 20,
  valorPropiedadPromedio: 150000,
},

Cuba: {
  moneda: "CUP",
  simbolo: "$",
  nombreDivisa: "Peso cubano",
  codigoISO: "CUP",
  tasaCreditoConsumo: 20,
  tasaCreditoAuto: 18,
  tasaCreditoVivienda: 12,
  tasaInversion: 7,
  valorPropiedadPromedio: 300000,
},

República Dominicana: {
  moneda: "DOP",
  simbolo: "RD$",
  nombreDivisa: "Peso dominicano",
  codigoISO: "DOP",
  tasaCreditoConsumo: 22,
  tasaCreditoAuto: 20,
  tasaCreditoVivienda: 14,
  tasaInversion: 8,
  valorPropiedadPromedio: 4500000,
},

Haití: {
  moneda: "HTG",
  simbolo: "G",
  nombreDivisa: "Gourde haitiano",
  codigoISO: "HTG",
  tasaCreditoConsumo: 30,
  tasaCreditoAuto: 28,
  tasaCreditoVivienda: 18,
  tasaInversion: 10,
  valorPropiedadPromedio: 1500000,
},

Jamaica: {
  moneda: "JMD",
  simbolo: "J$",
  nombreDivisa: "Dólar jamaiquino",
  codigoISO: "JMD",
  tasaCreditoConsumo: 25,
  tasaCreditoAuto: 22,
  tasaCreditoVivienda: 15,
  tasaInversion: 9,
  valorPropiedadPromedio: 8000000,
},

Trinidad y Tobago: {
  moneda: "TTD",
  simbolo: "TT$",
  nombreDivisa: "Dólar trinitense",
  codigoISO: "TTD",
  tasaCreditoConsumo: 18,
  tasaCreditoAuto: 16,
  tasaCreditoVivienda: 10,
  tasaInversion: 7,
  valorPropiedadPromedio: 1200000,
},

Barbados: {
  moneda: "BBD",
  simbolo: "Bds$",
  nombreDivisa: "Dólar barbadense",
  codigoISO: "BBD",
  tasaCreditoConsumo: 15,
  tasaCreditoAuto: 13,
  tasaCreditoVivienda: 9,
  tasaInversion: 6.5,
  valorPropiedadPromedio: 1000000,
},

Bahamas: {
  moneda: "BSD",
  simbolo: "$",
  nombreDivisa: "Dólar bahameño",
  codigoISO: "BSD",
  tasaCreditoConsumo: 14,
  tasaCreditoAuto: 12,
  tasaCreditoVivienda: 8,
  tasaInversion: 6,
  valorPropiedadPromedio: 200000,
},

